name: Build and Deploy Vue

on:
  workflow_dispatch:
  push:
    branches:
      - main  # 当代码推送到 main 分支触发

jobs:
  build-and-push-docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}

    steps:
      # Step 1: 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: 登录 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Generate tag
      - name: Generate tag
        id: tag
        run: |
          TAG=$(date +'%Y-%m-%d')-${{ github.run_number }}
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      # Step 4: 构建 Docker 镜像
      - name: Build Docker image
        run: docker build -t hauchenglee/xiaobaobei-web-compare-vue:${{ env.TAG }} .

      # Step 5: 推送 Docker 镜像到 Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push hauchenglee/xiaobaobei-web-compare-vue:${{ env.TAG }}

  deploy-to-centos:
    name: Deploy to CentOS Server
    runs-on: ubuntu-latest
    needs: build-and-push-docker  # 依赖上一个任务完成后再执行

    steps:
      # Step 1: 使用 SSH 部署到远程服务器
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOSTNAME }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            docker pull hauchenglee/xiaobaobei-web-compare-vue:${{ needs.build-and-push-docker.outputs.tag }}
            cd /opt/xiaobaobei-web-compare
            echo "VERSION=${{ needs.build-and-push-docker.outputs.tag }}" > .env
            docker compose pull vue
            docker compose up -d vue